name: download_data_eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.2.1
  - seaborn=0.9.0
  - pandas=1.2.3
  - pip=20.3.3
  - matplotlib=3.5.1
  - pandas-profiling=3.1.0
  - scikit-learn=1.0.2
  - ipywidgets=7.6.5
  - jupyterlab_widgets=1.0.0
  - pip:
      - wandb==0.12.6
